---
- name: CS LAPI - Add LAPI local agent to LAPI
  ansible.builtin.command:
    cmd: "cscli machines add {{ inventory_hostname }} -p {{ cs_agent_password }} -u http://{{ cs_server_listen_uri }} --force"
  become: true
  changed_when: false

- name: CS LAPI - Get current Machines (Agents)
  ansible.builtin.command:
    cmd: "cscli machines list --output json"
  register: machines_list
  changed_when: false

- name: CS LAPI - Create Machines fact
  ansible.builtin.set_fact:
    fact_machines_list: "{{ machines_list.stdout | from_json }}"

- name: CS LAPI - Add Machines (Agents)
  ansible.builtin.command:
    cmd: "cscli machines add {{ item }} -p {{ cs_agent_password }} -u http://{{ cs_server_listen_uri }} -f /dev/null --force"
  with_items: "{{ cs_agents }}"
  register: machines_install
  changed_when: false
  become: true
  when:
    - cs_agents is defined and cs_agents | length > 0
    - item not in fact_machines_list | json_query('[].machineId')

- name: CS LAPI - Remove Machines (Agents)
  ansible.builtin.command:
    cmd: "cscli machines remove {{ item }}"
  with_items: "{{ fact_machines_list | json_query('[].machineId') }}"
  register: machines_remove
  changed_when: false
  become: true
  when:
    - cs_agents is defined and cs_agents | length > 0
    - item not in cs_agents
    - item not in inventory_hostname

- name: CS LAPI - Get current Bouncers
  ansible.builtin.command:
    cmd: "cscli bouncers list --output json"
  register: bouncers_list
  changed_when: false

- name: CS LAPI - Create Bouncers fact
  ansible.builtin.set_fact:
    fact_bouncers_list: "{{ bouncers_list.stdout | from_json }}"

- name: CS LAPI - Add Bouncers
  ansible.builtin.command:
    cmd: "cscli bouncers add {{ item.name }} -k {{ item.api_key }}"
  with_items: "{{ cs_bouncers }}"
  changed_when: false
  become: true
  when:
    - cs_bouncers is defined and cs_bouncers | length > 0
    - item.name not in fact_bouncers_list | json_query('[].name')

- name: CS LAPI - Remove Bouncers
  ansible.builtin.command:
    cmd: "cscli bouncers delete {{ item }}"
  with_items: "{{ fact_bouncers_list | json_query('[].name') }}"
  changed_when: false
  become: true
  when:
    - cs_bouncers is defined and cs_bouncers | length > 0
    - item not in cs_bouncers | json_query('[].name')
