---
- name: CS LAPI - Add LAPI local agent to LAPI
  ansible.builtin.command:
    cmd: "cscli machines add {{ inventory_hostname }} -p {{ cs_agent_password }} -u http://{{ cs_server_listen_uri }} --force"
  become: true
  changed_when: false

- name: CS LAPI - Get current Machines (Agents)
  ansible.builtin.command:
    cmd: "cscli machines list --output json"
  register: machines_list
  changed_when: false

- name: CS LAPI - Create Machines fact
  ansible.builtin.set_fact:
    fact_machines_list: "{{ machines_list.stdout | from_json }}"

- name: CS LAPI - Add Machines (Agents)
  ansible.builtin.command:
    cmd: "cscli machines add {{ item }} -p {{ cs_agent_password }} -u http://{{ cs_server_listen_uri }} -f /dev/null --force"
  with_items: "{{ cs_agents }}"
  register: machines_install
  changed_when: false
  become: true
  when:
    - cs_agents is defined and cs_agents | length > 0
    - item not in fact_machines_list | json_query('[].machineId')

- name: CS Plugins - Remove Machines (Agents)
  ansible.builtin.command:
    cmd: "cscli machines remove {{ item }}"
  with_items: "{{ fact_machines_list | json_query('[].machineId') }}"
  register: machines_remove
  changed_when: false
  become: true
  when:
    - cs_agents is defined and cs_agents | length > 0
    - item not in cs_agents
    - item not in inventory_hostname
